export const INDEX = '/'
export const HOME = '/home'
export const SIGNUP = '/signup'
export const LOGIN = '/login'
export const SIMPLETABLE = '/chartstable'
export const CHART = '/chart'
export const EDITOR = '/editor'
export const DEVICE = '/device/:id'
